dist: xenial
language: python
python:
  - "3.7"  

env:
  - DACE_optimizer_automatic_strict_transformations=1
  - DACE_optimizer_automatic_strict_transformations=0

# Dependencies
before_install:
  - sudo apt-get install libyaml-dev cmake

install:
  - pip install .

script: NOSTATUSBAR=1 ./test_all.sh
